// UI 色卡数据
export const UI_PALETTES = {
  'Flat UI': [
    { name: 'Turquoise', hex: '#1ABC9C' },
    { name: 'Green Sea', hex: '#16A085' },
    { name: 'Emerald', hex: '#2ECC71' },
    { name: 'Nephritis', hex: '#27AE60' },
    { name: 'Peter River', hex: '#3498DB' },
    { name: 'Belize Hole', hex: '#2980B9' },
    { name: 'Amethyst', hex: '#9B59B6' },
    { name: 'Wisteria', hex: '#8E44AD' },
    { name: 'Wet Asphalt', hex: '#34495E' },
    { name: 'Midnight Blue', hex: '#2C3E50' },
    { name: 'Sun Flower', hex: '#F1C40F' },
    { name: 'Orange', hex: '#F39C12' },
    { name: 'Carrot', hex: '#E67E22' },
    { name: 'Pumpkin', hex: '#D35400' },
    { name: 'Alizarin', hex: '#E74C3C' },
    { name: 'Pomegranate', hex: '#C0392B' },
    { name: 'Clouds', hex: '#ECF0F1' },
    { name: 'Silver', hex: '#BDC3C7' },
    { name: 'Concrete', hex: '#95A5A6' },
    { name: 'Asbestos', hex: '#7F8C8D' },
  ],
  'Material Design': [
    { name: 'Red 500', hex: '#F44336' },
    { name: 'Pink 500', hex: '#E91E63' },
    { name: 'Purple 500', hex: '#9C27B0' },
    { name: 'Deep Purple 500', hex: '#673AB7' },
    { name: 'Indigo 500', hex: '#3F51B5' },
    { name: 'Blue 500', hex: '#2196F3' },
    { name: 'Light Blue 500', hex: '#03A9F4' },
    { name: 'Cyan 500', hex: '#00BCD4' },
    { name: 'Teal 500', hex: '#009688' },
    { name: 'Green 500', hex: '#4CAF50' },
    { name: 'Light Green 500', hex: '#8BC34A' },
    { name: 'Lime 500', hex: '#CDDC39' },
    { name: 'Yellow 500', hex: '#FFEB3B' },
    { name: 'Amber 500', hex: '#FFC107' },
    { name: 'Orange 500', hex: '#FF9800' },
    { name: 'Deep Orange 500', hex: '#FF5722' },
    { name: 'Brown 500', hex: '#795548' },
    { name: 'Grey 500', hex: '#9E9E9E' },
    { name: 'Blue Grey 500', hex: '#607D8B' },
  ],
  'Ant Design': [
    { name: 'Dust Red', hex: '#F5222D' },
    { name: 'Volcano', hex: '#FA541C' },
    { name: 'Sunset Orange', hex: '#FA8C16' },
    { name: 'Calendula Gold', hex: '#FAAD14' },
    { name: 'Sunrise Yellow', hex: '#FADB14' },
    { name: 'Lime', hex: '#A0D911' },
    { name: 'Polar Green', hex: '#52C41A' },
    { name: 'Cyan', hex: '#13C2C2' },
    { name: 'Daybreak Blue', hex: '#1890FF' },
    { name: 'Geek Blue', hex: '#2F54EB' },
    { name: 'Golden Purple', hex: '#722ED1' },
    { name: 'Magenta', hex: '#EB2F96' },
  ],
};

// 中国传统色
export const CHINESE_COLORS = [
  { name: '胭脂', hex: '#9D2933', pinyin: 'yanzhi' },
  { name: '朱红', hex: '#FF4C00', pinyin: 'zhuhong' },
  { name: '妃色', hex: '#ED5736', pinyin: 'feise' },
  { name: '赤', hex: '#C3272B', pinyin: 'chi' },
  { name: '银红', hex: '#F05654', pinyin: 'yinhong' },
  { name: '石榴红', hex: '#F20C00', pinyin: 'shiliuhong' },
  { name: '樱桃色', hex: '#C93756', pinyin: 'yingtaose' },
  { name: '海棠红', hex: '#DB5A6B', pinyin: 'haitanghong' },
  { name: '嫣红', hex: '#EF7A82', pinyin: 'yanhong' },
  { name: '洋红', hex: '#FF0097', pinyin: 'yanghong' },
  { name: '品红', hex: '#F00056', pinyin: 'pinhong' },
  { name: '桃红', hex: '#F47983', pinyin: 'taohong' },
  { name: '粉红', hex: '#FFB3A7', pinyin: 'fenhong' },
  { name: '橙色', hex: '#FA8C35', pinyin: 'chengse' },
  { name: '橘黄', hex: '#FF8936', pinyin: 'juhuang' },
  { name: '橘红', hex: '#FF7500', pinyin: 'juhong' },
  { name: '杏黄', hex: '#FFA631', pinyin: 'xinghuang' },
  { name: '金黄', hex: '#F0C239', pinyin: 'jinhuang' },
  { name: '鹅黄', hex: '#FFF143', pinyin: 'ehuang' },
  { name: '柠檬黄', hex: '#FFF000', pinyin: 'ningmenghuang' },
  { name: '嫩绿', hex: '#BDDD22', pinyin: 'nenlv' },
  { name: '柳绿', hex: '#AFDD22', pinyin: 'liulv' },
  { name: '葱绿', hex: '#9ED900', pinyin: 'conglv' },
  { name: '豆绿', hex: '#9ED048', pinyin: 'doulv' },
  { name: '青葱', hex: '#0AA344', pinyin: 'qingcong' },
  { name: '松绿', hex: '#057748', pinyin: 'songlv' },
  { name: '竹青', hex: '#789262', pinyin: 'zhuqing' },
  { name: '青色', hex: '#00E09E', pinyin: 'qingse' },
  { name: '碧色', hex: '#1BD1A5', pinyin: 'bise' },
  { name: '翠绿', hex: '#00E079', pinyin: 'cuilv' },
  { name: '湖绿', hex: '#25F8CB', pinyin: 'hulv' },
  { name: '艾绿', hex: '#A4E2C6', pinyin: 'ailv' },
  { name: '天青', hex: '#C0EBD7', pinyin: 'tianqing' },
  { name: '霁青', hex: '#4C8DAE', pinyin: 'jiqing' },
  { name: '石青', hex: '#7BCFA6', pinyin: 'shiqing' },
  { name: '靛青', hex: '#177CB0', pinyin: 'dianqing' },
  { name: '靛蓝', hex: '#065279', pinyin: 'dianlan' },
  { name: '碧蓝', hex: '#3EEDE7', pinyin: 'bilan' },
  { name: '蔚蓝', hex: '#70F3FF', pinyin: 'weilan' },
  { name: '宝蓝', hex: '#4B5CC4', pinyin: 'baolan' },
  { name: '藏蓝', hex: '#3B2E7E', pinyin: 'canglan' },
  { name: '黛', hex: '#4A4266', pinyin: 'dai' },
  { name: '黛绿', hex: '#426666', pinyin: 'dailv' },
  { name: '黛蓝', hex: '#425066', pinyin: 'dailan' },
  { name: '紫色', hex: '#8D4BBB', pinyin: 'zise' },
  { name: '紫酱', hex: '#815463', pinyin: 'zijiang' },
  { name: '酱紫', hex: '#815476', pinyin: 'jiangzi' },
  { name: '紫檀', hex: '#4C221B', pinyin: 'zitan' },
  { name: '绀青', hex: '#003371', pinyin: 'ganqing' },
  { name: '丁香色', hex: '#CCA4E3', pinyin: 'dingxiangse' },
  { name: '藕色', hex: '#EDD1D8', pinyin: 'ouse' },
  { name: '藕荷色', hex: '#E4C6D0', pinyin: 'ouhese' },
];

// 日本传统色
export const JAPANESE_COLORS = [
  { name: '桜色', hex: '#FEDFE1', romaji: 'sakurairo' },
  { name: '桃色', hex: '#F09199', romaji: 'momoiro' },
  { name: '撫子色', hex: '#EE827C', romaji: 'nadeshikoiro' },
  { name: '紅色', hex: '#D7003A', romaji: 'beniiro' },
  { name: '朱色', hex: '#EB6101', romaji: 'shuiro' },
  { name: '柿色', hex: '#ED6D3D', romaji: 'kakiiro' },
  { name: '山吹色', hex: '#F8B500', romaji: 'yamabukiiro' },
  { name: '黄金色', hex: '#E6B422', romaji: 'koganeiro' },
  { name: '若草色', hex: '#C3D825', romaji: 'wakakusairo' },
  { name: '萌黄', hex: '#AAD500', romaji: 'moegi' },
  { name: '若竹色', hex: '#68BE8D', romaji: 'wakatakeiro' },
  { name: '青竹色', hex: '#7EBEAB', romaji: 'aotakeiro' },
  { name: '水色', hex: '#BCE2E8', romaji: 'mizuiro' },
  { name: '空色', hex: '#A0D8EF', romaji: 'sorairo' },
  { name: '浅葱色', hex: '#00A3AF', romaji: 'asagiiro' },
  { name: '藍色', hex: '#165E83', romaji: 'aiiro' },
  { name: '紺色', hex: '#223A70', romaji: 'koniro' },
  { name: '藤色', hex: '#A59ACA', romaji: 'fujiiro' },
  { name: '菫色', hex: '#7058A3', romaji: 'sumireiro' },
  { name: '江戸紫', hex: '#745399', romaji: 'edomurasaki' },
];
