export type ToolType = 'inline' | 'window' | 'link';

export interface ToolDefinition {
  id: string;
  name: string;
  description: string;
  keywords: string[];
  categoryId: string;
  icon: string;
  type: ToolType;
  windowLabel?: string;
  windowWidth?: number;
  windowHeight?: number;
  linkUrl?: string;
  inlineComponent?: string;
}

const tools: ToolDefinition[] = [
  {
    id: 'qrcode',
    name: '二维码生成',
    description: '生成文本、URL、名片、WiFi、电话等多种类型二维码',
    keywords: ['二维码', 'qrcode', 'qr', '名片', 'vcard', 'wifi', '扫码', '生成'],
    categoryId: 'efficiency',
    icon: '🎨',
    type: 'window',
    windowLabel: 'tool-qrcode',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'unit-converter',
    name: '单位换算',
    description: '长度、重量、温度、面积、体积等单位转换',
    keywords: [
      '单位',
      '换算',
      '转换',
      'unit',
      'convert',
      '英寸',
      '厘米',
      '磅',
      '克',
      '温度',
      '长度',
      '重量',
    ],
    categoryId: 'efficiency',
    icon: '🔄',
    type: 'window',
    windowLabel: 'tool-unit-converter',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'speed-test',
    name: '网速测试',
    description: '多样本并发测速、30 天历史、质量评分、趋势统计和周期测试',
    keywords: [
      '网速',
      '测速',
      'speed',
      'test',
      '带宽',
      '上传',
      '下载',
      'speedtest',
      '网络速度',
      'myspeed',
      '历史记录',
      '趋势',
      '质量评分',
    ],
    categoryId: 'network',
    icon: '⚡',
    type: 'window',
    windowLabel: 'tool-speed-test',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'ping',
    name: 'Ping 测试',
    description: '网络延迟测试、丢包率分析、抖动监控、实时图表展示',
    keywords: ['ping', '延迟', '丢包', '网络', '测试', 'latency', 'network', '抖动'],
    categoryId: 'network',
    icon: '📡',
    type: 'window',
    windowLabel: 'tool-ping',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'dns-query',
    name: 'DNS 查询',
    description: 'DNS 记录查询（A/AAAA/MX/TXT），支持多个 DNS 服务器',
    keywords: ['dns', '域名', '解析', 'lookup', 'query', 'A记录', 'MX', 'TXT', 'AAAA'],
    categoryId: 'network',
    icon: '🔍',
    type: 'window',
    windowLabel: 'tool-dns-query',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'ip-info',
    name: 'IP 信息查询',
    description: '查询 IP 地址的地理位置、运营商、时区等信息',
    keywords: ['ip', '地理位置', '运营商', 'isp', '查询', 'location', '公网IP', '本机IP'],
    categoryId: 'network',
    icon: '🌐',
    type: 'window',
    windowLabel: 'tool-ip-info',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'port-scan',
    name: '端口扫描',
    description: '扫描主机开放端口，识别常见服务',
    keywords: ['端口', 'port', '扫描', 'scan', '服务', 'service', '开放端口'],
    categoryId: 'network',
    icon: '🔌',
    type: 'window',
    windowLabel: 'tool-port-scan',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'traceroute',
    name: 'Traceroute 路由追踪',
    description: '追踪目标路由路径，显示每跳探测、丢包、抖动，并支持 MTR 多轮统计',
    keywords: [
      'traceroute',
      'tracert',
      '路由',
      '追踪',
      'route',
      'trace',
      'mtr',
      'nexttrace',
      '网络诊断',
      '跳数',
      '丢包',
      '抖动',
    ],
    categoryId: 'network',
    icon: '🗺️',
    type: 'window',
    windowLabel: 'tool-traceroute',
    windowWidth: 1280,
    windowHeight: 820,
  },
  {
    id: 'hosts-editor',
    name: 'Hosts 编辑',
    description: '查看和编辑 Windows Hosts 文件，支持普通保存和管理员授权保存',
    keywords: ['hosts', 'host', '域名', '解析', '系统', 'windows', '管理员', 'dns'],
    categoryId: 'system',
    icon: '🧩',
    type: 'window',
    windowLabel: 'tool-hosts-editor',
    windowWidth: 1100,
    windowHeight: 760,
  },
  {
    id: 'shutdown-scheduler',
    name: '定时关机',
    description: '创建或取消 Windows 定时关机/重启任务，支持常用时间快捷设置',
    keywords: ['关机', '定时关机', '重启', 'shutdown', 'restart', 'windows', '系统'],
    categoryId: 'system',
    icon: '⏻',
    type: 'window',
    windowLabel: 'tool-shutdown-scheduler',
    windowWidth: 980,
    windowHeight: 640,
  },
  {
    id: 'startup-manager',
    name: '开机启动管理',
    description: '查看和启停 Windows Run 注册表与启动文件夹中的开机启动项',
    keywords: ['开机启动', '启动项', 'startup', 'run', 'windows', '系统', '自启动'],
    categoryId: 'system',
    icon: '🚀',
    type: 'window',
    windowLabel: 'tool-startup-manager',
    windowWidth: 1180,
    windowHeight: 760,
  },
  {
    id: 'file-unlocker',
    name: '解除占用',
    description: '检查文件或文件夹占用进程，并支持结束占用进程',
    keywords: ['解除占用', '文件占用', '无法删除', 'unlock', 'lock', '进程', 'windows', '系统'],
    categoryId: 'system',
    icon: '🔓',
    type: 'window',
    windowLabel: 'tool-file-unlocker',
    windowWidth: 1080,
    windowHeight: 720,
  },
  {
    id: 'force-delete',
    name: '强制删除',
    description: '强制删除文件或文件夹，处理只读和残留目录等常见删除失败问题',
    keywords: ['强制删除', '删除文件', '删除文件夹', 'force delete', 'remove', '只读', '系统'],
    categoryId: 'system',
    icon: '🗑️',
    type: 'window',
    windowLabel: 'tool-force-delete',
    windowWidth: 960,
    windowHeight: 680,
  },
  {
    id: 'large-files',
    name: '大文件查找',
    description: '扫描指定目录中的大文件，按体积排序并支持定位到资源管理器',
    keywords: ['大文件', '磁盘空间', '查找文件', 'large file', 'disk', 'storage', '系统'],
    categoryId: 'system',
    icon: '📦',
    type: 'window',
    windowLabel: 'tool-large-files',
    windowWidth: 1180,
    windowHeight: 760,
  },
  {
    id: 'junk-cleaner',
    name: '垃圾清理',
    description: '扫描并清理常见临时文件、网页缓存和崩溃转储文件',
    keywords: ['垃圾清理', '临时文件', '缓存', 'temp', 'cache', 'clean', '磁盘清理', '系统'],
    categoryId: 'system',
    icon: '🧹',
    type: 'window',
    windowLabel: 'tool-junk-cleaner',
    windowWidth: 1120,
    windowHeight: 720,
  },
  {
    id: 'dns-switch',
    name: 'DNS 快速切换',
    description: '读取本机网卡，一键切换常用 DNS、恢复自动获取并刷新 DNS 缓存',
    keywords: ['dns', '网卡', '网络', '解析', 'cloudflare', 'google', '阿里', '腾讯', '系统'],
    categoryId: 'system',
    icon: '🌐',
    type: 'window',
    windowLabel: 'tool-dns-switch',
    windowWidth: 1180,
    windowHeight: 760,
  },
  {
    id: 'network-repair',
    name: '断网急救箱',
    description: '一键诊断网卡、网关、DNS、代理和 Hosts，并分项执行网络修复',
    keywords: [
      '断网',
      '急救箱',
      '网络修复',
      '网络诊断',
      'winsock',
      'tcpip',
      'dns',
      '代理',
      'hosts',
      'ipconfig',
      '系统',
    ],
    categoryId: 'system',
    icon: '🛟',
    type: 'window',
    windowLabel: 'tool-network-repair',
    windowWidth: 1280,
    windowHeight: 820,
  },
  {
    id: 'environment-variables',
    name: '环境变量 / PATH',
    description: '分条管理用户和系统 PATH，查看和编辑 Windows 环境变量',
    keywords: ['环境变量', 'path', 'PATH', '变量', '开发环境', '系统变量', '系统'],
    categoryId: 'system',
    icon: '🧬',
    type: 'window',
    windowLabel: 'tool-environment-variables',
    windowWidth: 1220,
    windowHeight: 780,
  },
  {
    id: 'context-menu-manager',
    name: '右键菜单管理',
    description: '管理桌面、文件夹和文件右键菜单，支持添加常用命令和删除无用菜单',
    keywords: ['右键菜单', 'context menu', '注册表', '菜单', 'open with', '系统'],
    categoryId: 'system',
    icon: '🖱️',
    type: 'window',
    windowLabel: 'tool-context-menu-manager',
    windowWidth: 1220,
    windowHeight: 780,
  },
  {
    id: 'services-manager',
    name: '系统服务管理',
    description: '查看 Windows 服务状态、启动类型和路径，支持启动、停止、重启和调整启动类型',
    keywords: ['服务', 'service', 'services', '启动类型', '停止服务', '系统'],
    categoryId: 'system',
    icon: '🛠️',
    type: 'window',
    windowLabel: 'tool-services-manager',
    windowWidth: 1280,
    windowHeight: 780,
  },
  {
    id: 'scheduled-tasks',
    name: '计划任务管理',
    description: '查看 Windows 计划任务触发器和动作，支持启用、禁用、运行和停止',
    keywords: ['计划任务', 'scheduled task', 'task scheduler', '定时任务', '开机任务', '系统'],
    categoryId: 'system',
    icon: '📅',
    type: 'window',
    windowLabel: 'tool-scheduled-tasks',
    windowWidth: 1280,
    windowHeight: 780,
  },
  {
    id: 'installed-apps',
    name: '软件卸载管理',
    description: '读取已安装软件列表，查看安装信息并调用软件原卸载程序',
    keywords: ['卸载', '软件', 'installed apps', 'uninstall', '程序', '应用', '系统'],
    categoryId: 'system',
    icon: '📦',
    type: 'window',
    windowLabel: 'tool-installed-apps',
    windowWidth: 1180,
    windowHeight: 760,
  },
  {
    id: 'system-info',
    name: '系统信息',
    description: '查看操作系统、硬件、磁盘和网络适配器概要，支持复制报告',
    keywords: ['系统信息', '硬件', 'CPU', '内存', '显卡', '磁盘', '电脑配置', '系统'],
    categoryId: 'system',
    icon: '💻',
    type: 'window',
    windowLabel: 'tool-system-info',
    windowWidth: 1180,
    windowHeight: 760,
  },
  {
    id: 'windows-update',
    name: 'Windows 更新辅助',
    description: '查看更新服务和近期补丁，支持打开设置、重启服务和清理下载缓存',
    keywords: ['windows update', '更新', '补丁', 'wuauserv', 'SoftwareDistribution', '系统'],
    categoryId: 'system',
    icon: '🪟',
    type: 'window',
    windowLabel: 'tool-windows-update',
    windowWidth: 1180,
    windowHeight: 760,
  },
  {
    id: 'wsl-dashboard',
    name: 'WSL 管理面板',
    description: '管理 WSL 发行版，支持启动、暂停/停止、重启、删除、版本转换、文件访问和导出备份',
    keywords: [
      'wsl',
      'linux',
      'ubuntu',
      '发行版',
      '子系统',
      'docker',
      'terminal',
      '系统',
      '暂停',
      '删除',
      'unregister',
      '备份',
    ],
    categoryId: 'system',
    icon: '🐧',
    type: 'window',
    windowLabel: 'tool-wsl-dashboard',
    windowWidth: 1280,
    windowHeight: 820,
  },
  {
    id: 'driver-manager',
    name: '驱动管理',
    description: '按显卡、网卡、音频等分类管理驱动包，支持检查更新、扫描硬件、导出和删除',
    keywords: [
      '驱动',
      'driver',
      'driver store',
      'pnputil',
      'oem.inf',
      '硬件',
      '设备',
      '系统',
      '显卡',
      '网卡',
      '更新',
      '可选更新',
    ],
    categoryId: 'system',
    icon: '🧩',
    type: 'window',
    windowLabel: 'tool-driver-manager',
    windowWidth: 1360,
    windowHeight: 840,
  },
  {
    id: 'printer-manager',
    name: '打印机管理',
    description: '检测打印机连接状态和真实可用性，管理打印队列、默认打印机、测试页、扫描设备和故障处理入口',
    keywords: [
      '打印机',
      'printer',
      'print',
      '打印队列',
      '默认打印机',
      '测试页',
      '扫描',
      'scanner',
      'scan',
      'wia',
      'twain',
      '系统',
    ],
    categoryId: 'system',
    icon: '🖨️',
    type: 'window',
    windowLabel: 'tool-printer-manager',
    windowWidth: 1360,
    windowHeight: 840,
  },
  {
    id: 'system-monitor',
    name: '系统监控信息',
    description: '分栏查看系统资源、进程、服务、TCP 连接、磁盘和网卡活动快照',
    keywords: [
      '系统监控',
      'system informer',
      'process',
      '进程',
      '服务',
      '网络连接',
      'tcp',
      '性能',
      '资源',
      '系统',
      '分类',
      '明细',
    ],
    categoryId: 'system',
    icon: '📈',
    type: 'window',
    windowLabel: 'tool-system-monitor',
    windowWidth: 1380,
    windowHeight: 860,
  },
  {
    id: 'date-calculator',
    name: '时间差计算',
    description: '日期差计算、工作日计算、日期加减、时间段差计算',
    keywords: ['时间', '日期', '计算', '工作日', '时间差', 'date', 'time', 'calculator', '天数'],
    categoryId: 'efficiency',
    icon: '🕒',
    type: 'window',
    windowLabel: 'tool-date-calculator',
    windowWidth: 700,
    windowHeight: 600,
  },
  {
    id: 'todo',
    name: '待办事项',
    description: '四象限任务管理（艾森豪威尔矩阵），支持拖拽、截止日期、优先级',
    keywords: ['待办', '任务', 'todo', 'task', '四象限', '艾森豪威尔', '时间管理', 'GTD'],
    categoryId: 'efficiency',
    icon: '✅',
    type: 'window',
    windowLabel: 'tool-todo',
    windowWidth: 1000,
    windowHeight: 700,
  },
  {
    id: 'project-manager',
    name: '项目管理',
    description: '项目进度、任务清单、负责人、节点和备注统一管理，适合日常办公推进',
    keywords: ['项目', '项目管理', 'project', '管理', '进度', '任务', '里程碑', '协作'],
    categoryId: 'efficiency',
    icon: '📁',
    type: 'window',
    windowLabel: 'tool-project-manager',
    windowWidth: 1360,
    windowHeight: 860,
  },
  {
    id: 'ecommerce-store-manager',
    name: '跨境电商店铺管理',
    description: '集中记录 Amazon、Walmart、SHEIN、Temu、TikTok 等店铺主体、法人、状态、运营指标和维护记录',
    keywords: [
      '跨境电商',
      '店铺管理',
      '电商店铺',
      'amazon',
      'walmart',
      'shein',
      'temu',
      'tiktok',
      '运营',
      '主体',
      '法人',
      '注册时间',
      '店铺状态',
      '风控',
      '维护',
    ],
    categoryId: 'efficiency',
    icon: '🏬',
    type: 'window',
    windowLabel: 'tool-ecommerce-store-manager',
    windowWidth: 1440,
    windowHeight: 900,
  },
  {
    id: 'ecommerce-appeal-ledger',
    name: '跨境电商申诉记录',
    description: '管理代申诉业务台账、对接微信、店铺主体、账号信息、申诉进度、收费结算和结果反馈',
    keywords: [
      '跨境电商',
      '申诉',
      '申诉记录',
      '店铺申诉',
      '亚马逊申诉',
      'walmart申诉',
      '收费',
      '结算',
      '对接微信',
      '暂停原因',
      '结果反馈',
    ],
    categoryId: 'efficiency',
    icon: '🧾',
    type: 'window',
    windowLabel: 'tool-ecommerce-appeal-ledger',
    windowWidth: 1480,
    windowHeight: 900,
  },
  {
    id: 'esim-manager',
    name: '手机号码 eSIM 管理',
    description: '管理多国家手机号码、eSIM / SIM 卡有效期、续费提醒、用途资料和续费记录',
    keywords: [
      '手机号码',
      '手机号',
      '号码管理',
      'eSIM',
      'esim',
      'SIM',
      'sim卡',
      '保号',
      '续费',
      '到期',
      '提醒',
      '国家',
      '短信',
      'telegram',
      '验证',
    ],
    categoryId: 'efficiency',
    icon: '📱',
    type: 'window',
    windowLabel: 'tool-esim-manager',
    windowWidth: 1440,
    windowHeight: 900,
  },
  {
    id: 'subscription-manager',
    name: '订阅管理',
    description: '管理循环订阅、续费提醒、分类预算、多币种折算和费用统计',
    keywords: [
      '订阅',
      '订阅管理',
      'subscription',
      'wallos',
      '会员',
      '续费',
      '扣费',
      '预算',
      '账单',
      '提醒',
      '多币种',
      '费用统计',
    ],
    categoryId: 'efficiency',
    icon: '📆',
    type: 'window',
    windowLabel: 'tool-subscription-manager',
    windowWidth: 1440,
    windowHeight: 900,
  },
  {
    id: 'rss-reader',
    name: 'RSS 阅读器',
    description: '本地 RSS/Atom 订阅阅读器，支持分类、已读、收藏、稍后读、搜索和 OPML 导入导出',
    keywords: ['rss', 'atom', 'feed', '订阅源', '阅读器', '新闻', '资讯', 'opml', '收藏', '稍后读'],
    categoryId: 'efficiency',
    icon: '📰',
    type: 'window',
    windowLabel: 'tool-rss-reader',
    windowWidth: 1440,
    windowHeight: 900,
  },
  {
    id: 'resume-generator',
    name: '简历生成器',
    description: '结构化编辑简历，实时 A4 预览，支持模板切换、JSON/HTML/Markdown 导出',
    keywords: ['简历', 'resume', 'cv', '求职', '工作经历', '项目经历', '教育经历', '导出', '打印'],
    categoryId: 'efficiency',
    icon: '📄',
    type: 'window',
    windowLabel: 'tool-resume-generator',
    windowWidth: 1440,
    windowHeight: 920,
  },
  {
    id: 'website-bookmarks',
    name: '网址收藏',
    description: '支持多级分类的网址导航和常用站点收藏，适合沉淀工作后台、文档和工具入口',
    keywords: ['网址', '收藏', '书签', '导航', 'bookmark', 'links', '网站', '常用网址'],
    categoryId: 'efficiency',
    icon: '🌐',
    type: 'window',
    windowLabel: 'tool-website-bookmarks',
    windowWidth: 1440,
    windowHeight: 900,
  },
  {
    id: 'file-rename',
    name: '批量重命名',
    description: '本地文件/文件夹批量重命名，支持模板、序号、日期、扩展名处理和正则替换',
    keywords: [
      '重命名',
      '批量重命名',
      '文件重命名',
      '文件夹重命名',
      'rename',
      'batch',
      '正则',
      'regex',
      '扩展名',
      '序号',
      '照片整理',
      '文件整理',
    ],
    categoryId: 'efficiency',
    icon: '🗂️',
    type: 'window',
    windowLabel: 'tool-file-rename',
    windowWidth: 1280,
    windowHeight: 820,
  },
  {
    id: 'auto-clicker',
    name: '超级连点器',
    description: '轻量鼠标连点器，支持全局快捷键、点击间隔、按键类型、双击和点击上限',
    keywords: [
      '连点器',
      '鼠标连点器',
      '超级连点器',
      'auto clicker',
      'clicker',
      '鼠标',
      '点击',
      '快捷键',
      '自动点击',
    ],
    categoryId: 'efficiency',
    icon: '🖱️',
    type: 'window',
    windowLabel: 'tool-auto-clicker',
    windowWidth: 1280,
    windowHeight: 760,
  },
  {
    id: 'password-manager',
    name: '密码管理器',
    description: '本地密码保险箱，支持加密保存、多 TOTP、网址、备注、自动锁定和剪贴板清理',
    keywords: [
      '密码',
      '密码管理',
      'password',
      'vault',
      'bitwarden',
      'totp',
      'otp',
      '2fa',
      '验证码',
      '密钥',
      '账号',
      '保险箱',
    ],
    categoryId: 'efficiency',
    icon: '🔐',
    type: 'window',
    windowLabel: 'tool-password-manager',
    windowWidth: 1280,
    windowHeight: 820,
  },
  {
    id: 'archive-manager',
    name: '压缩解压',
    description: '内置 7-Zip 引擎，支持文件/文件夹压缩、解压、密码和分卷',
    keywords: [
      '压缩',
      '解压',
      '压缩包',
      'zip',
      '7z',
      'rar',
      'tar',
      '密码压缩',
      'archive',
      'extract',
      'compress',
    ],
    categoryId: 'efficiency',
    icon: '🗜️',
    type: 'window',
    windowLabel: 'tool-archive-manager',
    windowWidth: 1180,
    windowHeight: 780,
  },
  {
    id: 'mind-map',
    name: '思维导图',
    description: '完整思维导图编辑器，支持结构布局、节点样式、图片备注、搜索替换和多格式导入导出',
    keywords: [
      '思维导图',
      '脑图',
      'mindmap',
      'mind map',
      'xmind',
      '大纲',
      '结构图',
      '流程整理',
      '知识管理',
      '导出',
    ],
    categoryId: 'efficiency',
    icon: '🧠',
    type: 'window',
    windowLabel: 'tool-mind-map',
    windowWidth: 1500,
    windowHeight: 920,
  },
  {
    id: 'flowchart',
    name: '流程图',
    description: '基于 React Flow / XYFlow 的流程图编辑器，支持节点连线、模板、自动布局和导入导出',
    keywords: [
      '流程图',
      'flowchart',
      'react flow',
      'xyflow',
      '节点',
      '连线',
      '审批流',
      '业务流程',
      '工作流',
      '导出',
    ],
    categoryId: 'efficiency',
    icon: '🔀',
    type: 'window',
    windowLabel: 'tool-flowchart',
    windowWidth: 1500,
    windowHeight: 920,
  },
  {
    id: 'whiteboard',
    name: '白板',
    description: '基于 tldraw 的完整白板，支持画笔、形状、便签、图片、连线、页面和本地保存',
    keywords: [
      '白板',
      '画板',
      'whiteboard',
      'tldraw',
      '手绘',
      '草图',
      '便签',
      '图片',
      '协作草稿',
      '导出',
    ],
    categoryId: 'efficiency',
    icon: '✏️',
    type: 'window',
    windowLabel: 'tool-whiteboard',
    windowWidth: 1500,
    windowHeight: 920,
  },
  {
    id: 'prompt-library',
    name: 'AI Prompt 库',
    description: '管理 AI 模型词资产，支持分类、标签、收藏，适合 AI 绘图、写作、编程等场景',
    keywords: [
      'prompt',
      'ai',
      '模型词',
      '提示词',
      'chatgpt',
      'claude',
      'midjourney',
      '提示',
      '模板',
    ],
    categoryId: 'ai',
    icon: '🤖',
    type: 'window',
    windowLabel: 'tool-prompt-library',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'skills-library',
    name: 'AI Skills 库',
    description: '管理 AI 能力包和工作流，包含完整的使用说明、触发场景、示例指令',
    keywords: ['skills', 'ai', '能力', '工作流', '自动化', 'workflow', '技能', '流程'],
    categoryId: 'ai',
    icon: '⚡',
    type: 'window',
    windowLabel: 'tool-skills-library',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'mcp-library',
    name: 'MCP 管理工具',
    description: '管理 AI 外部工具连接、MCP 服务和能力接口的配置管理工具',
    keywords: ['mcp', 'server', '服务', '工具', '接口', '连接', '配置', 'api'],
    categoryId: 'ai',
    icon: '🔌',
    type: 'window',
    windowLabel: 'tool-mcp-library',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'kiro-account-manager',
    name: 'Kiro 账号管理',
    description: '本地管理 Kiro 登录快照，支持本机导入、JSON 导入导出、标签和账号切换',
    keywords: ['kiro', '账号', '账户', 'account', 'token', '切换', '导入', '导出', 'ai'],
    categoryId: 'ai',
    icon: '🧠',
    type: 'window',
    windowLabel: 'tool-kiro-account-manager',
    windowWidth: 1220,
    windowHeight: 780,
  },
  {
    id: 'calculator',
    name: '计算器',
    description: '基础四则运算计算器',
    keywords: ['计算器', '计算', 'calc', 'calculator', '加减乘除'],
    categoryId: 'efficiency',
    icon: '🧮',
    type: 'window',
    windowLabel: 'tool-calculator',
    windowWidth: 320,
    windowHeight: 480,
  },
  {
    id: 'wechat-meme',
    name: '微信表情包转换',
    description: '把普通图片转成 GIF 并复制到微信可粘贴的文件剪贴板，适合快速发图做表情',
    keywords: ['微信', '表情包', 'gif', 'meme', 'weixin', 'wechat', '图片转表情', '剪贴板'],
    categoryId: 'efficiency',
    icon: '😄',
    type: 'window',
    windowLabel: 'tool-wechat-meme',
    windowWidth: 1280,
    windowHeight: 860,
  },
  {
    id: 'pinyin',
    name: '文字转拼音',
    description: '汉字转拼音，支持声调、首字母、多音字',
    keywords: ['拼音', '转拼音', 'pinyin', '汉字拼音', '注音'],
    categoryId: 'text',
    icon: '🔤',
    type: 'window',
    windowLabel: 'tool-pinyin',
    windowWidth: 520,
    windowHeight: 400,
  },
  {
    id: 'text-prefix',
    name: '批量添加前后缀',
    description: '批量为多行文本添加前缀和后缀，支持数字/字母/中文序号',
    keywords: ['前缀', '后缀', '批量', '序号', '文本处理', '添加前缀', '添加后缀', 'prefix'],
    categoryId: 'text',
    icon: '📝',
    type: 'window',
    windowLabel: 'tool-text-prefix',
    windowWidth: 780,
    windowHeight: 580,
  },
  {
    id: 'remove-linenum',
    name: '去行号工具',
    description: '自动去除多行文本中的行号，支持多种格式和自定义正则',
    keywords: ['去行号', '行号', '删除行号', '去除编号', 'linenum', '序号'],
    categoryId: 'text',
    icon: '🔢',
    type: 'window',
    windowLabel: 'tool-remove-linenum',
    windowWidth: 680,
    windowHeight: 520,
  },
  {
    id: 'url-extractor',
    name: 'URL 提取器',
    description: '从文本中提取 URL，支持按扩展名、域名过滤，自动去重',
    keywords: ['url', '链接', '提取', '网址', 'link', 'extract', '图片链接', '域名'],
    categoryId: 'text',
    icon: '🔗',
    type: 'window',
    windowLabel: 'tool-url-extractor',
    windowWidth: 860,
    windowHeight: 580,
  },
  {
    id: 'url-encode',
    name: 'URL 编解码',
    description: 'URL 编码与解码转换，支持批量处理、最小编码和全编码模式',
    keywords: [
      'url',
      '编码',
      '解码',
      'encode',
      'decode',
      'uri',
      'encodeURIComponent',
      'urlencode',
      'urldecode',
      '百分号',
    ],
    categoryId: 'text',
    icon: '🌐',
    type: 'window',
    windowLabel: 'tool-url-encode',
    windowWidth: 780,
    windowHeight: 520,
  },
  {
    id: 'url-parser',
    name: 'URL 解析',
    description: 'URL 解析工具，解析协议、主机、路径、查询参数等',
    keywords: ['url', '解析', 'parse', '域名', '参数', 'query', 'path', 'hostname', '链接'],
    categoryId: 'dev',
    icon: '🔗',
    type: 'window',
    windowLabel: 'tool-url-parser',
    windowWidth: 900,
    windowHeight: 700,
  },
  {
    id: 'base64',
    name: 'Base64 转换',
    description: '支持文本和图片的 Base64 编码与解码转换',
    keywords: [
      'base64',
      '编码',
      '解码',
      'encode',
      'decode',
      '图片',
      'image',
      '转换',
      'btoa',
      'atob',
    ],
    categoryId: 'text',
    icon: '🔐',
    type: 'window',
    windowLabel: 'tool-base64',
    windowWidth: 820,
    windowHeight: 580,
  },
  {
    id: 'line-processor',
    name: '换行处理',
    description: '删除换行、删除空行、合并空行、添加分隔符、拆分为行等简单实用的换行处理',
    keywords: [
      '换行',
      '空行',
      '删除',
      '合并',
      '拆分',
      '分割',
      '分隔符',
      'line',
      'break',
      'split',
      'empty',
      'separator',
      '批量',
    ],
    categoryId: 'text',
    icon: '📝',
    type: 'window',
    windowLabel: 'tool-line-processor',
    windowWidth: 820,
    windowHeight: 580,
  },
  {
    id: 'text-formatter',
    name: '一键排版',
    description: '清除 HTML 标签、样式、脚本、链接、广告，转换为干净整洁的文章',
    keywords: [
      '排版',
      '格式化',
      '清理',
      'format',
      'clean',
      'html',
      '标签',
      '样式',
      '脚本',
      '链接',
      '广告',
      '文章',
      '新闻',
      '编辑',
    ],
    categoryId: 'text',
    icon: '✨',
    type: 'window',
    windowLabel: 'tool-text-formatter',
    windowWidth: 1400,
    windowHeight: 800,
  },
  {
    id: 'text-deduplicate',
    name: '文本去重',
    description: '智能识别分隔符，一键去重清洗，支持 SQL、JSON 等多种输出格式',
    keywords: [
      '去重',
      '清洗',
      '名单',
      '手机号',
      '编号',
      'sku',
      '地址',
      'deduplicate',
      'unique',
      'clean',
      '分隔符',
      'sql',
      'json',
      '逗号',
      '顿号',
    ],
    categoryId: 'text',
    icon: '✨',
    type: 'window',
    windowLabel: 'tool-text-deduplicate',
    windowWidth: 1400,
    windowHeight: 800,
  },
  {
    id: 'case-converter',
    name: '大小写转换',
    description: '英文字母大小写转换，支持 10 种模式，APA Style 标题格式',
    keywords: [
      '大小写',
      '转换',
      'case',
      'upper',
      'lower',
      'title',
      'camel',
      'pascal',
      'snake',
      'kebab',
      '驼峰',
      '标题',
      '命名',
    ],
    categoryId: 'text',
    icon: '🔤',
    type: 'window',
    windowLabel: 'tool-case-converter',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'chinese-converter',
    name: '简繁转换',
    description: '中文简繁体转换，支持大陆、台湾、香港、日本用词',
    keywords: [
      '简体',
      '繁体',
      '简繁',
      '转换',
      'chinese',
      'traditional',
      'simplified',
      '台湾',
      '香港',
      '大陆',
      'opencc',
    ],
    categoryId: 'text',
    icon: '🀄',
    type: 'window',
    windowLabel: 'tool-chinese-converter',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'text-batch-replace',
    name: '批量替换',
    description: '文本批量查找替换，支持普通文本和正则表达式',
    keywords: ['替换', '查找', '批量', 'replace', 'find', 'regex', '正则', '文本处理', '规则'],
    categoryId: 'text',
    icon: '🔄',
    type: 'window',
    windowLabel: 'tool-text-batch-replace',
    windowWidth: 1400,
    windowHeight: 900,
  },
  {
    id: 'text-diff',
    name: '文本比较',
    description: '文本差异对比，支持字符、单词、行、段落、CSS、代码比较',
    keywords: ['比较', '对比', '差异', 'diff', 'compare', '文本', 'css', '代码', '段落'],
    categoryId: 'text',
    icon: '🔍',
    type: 'window',
    windowLabel: 'tool-text-diff',
    windowWidth: 1400,
    windowHeight: 900,
  },
  {
    id: 'html-editor',
    name: 'HTML 编辑器',
    description: '基于 UEditor Plus 的全功能富文本编辑器，支持表格、图片、公式、代码等',
    keywords: ['html', '富文本', '编辑器', 'ueditor', 'rich text', '排版', '文档'],
    categoryId: 'dev',
    icon: '🖊️',
    type: 'window',
    windowLabel: 'tool-html-editor',
    windowWidth: 1100,
    windowHeight: 720,
  },
  {
    id: 'md-editor',
    name: 'Markdown 编辑器',
    description: '基于 Vditor 的全功能 Markdown 编辑器，支持流程图、甘特图、数学公式、代码高亮',
    keywords: ['markdown', 'md', '编辑器', 'vditor', '流程图', '甘特图', '公式', '文档'],
    categoryId: 'dev',
    icon: '📄',
    type: 'window',
    windowLabel: 'tool-md-editor',
    windowWidth: 1100,
    windowHeight: 720,
  },
  {
    id: 'color-assistant',
    name: '颜色助手',
    description: '取色器、配色方案、UI色卡、传统色、渐变色生成、AI配色、色卡收藏管理',
    keywords: [
      '颜色',
      '取色',
      '配色',
      'color',
      'picker',
      '色卡',
      'palette',
      '渐变',
      'gradient',
      '传统色',
      'AI',
    ],
    categoryId: 'dev',
    icon: '🎨',
    type: 'window',
    windowLabel: 'tool-color-assistant',
    windowWidth: 900,
    windowHeight: 700,
  },
  {
    id: 'css',
    name: 'CSS 工具',
    description: 'CSS 美化、压缩、自动添加浏览器前缀、属性排序',
    keywords: ['css', '美化', '压缩', 'minify', 'beautify', 'autoprefixer', '前缀', '格式化'],
    categoryId: 'dev',
    icon: '🎨',
    type: 'window',
    windowLabel: 'tool-css',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'json',
    name: 'JSON 工具箱',
    description: 'JSON 格式化、压缩、对比、Schema 校验、转 TypeScript Interface',
    keywords: [
      'json',
      '格式化',
      '压缩',
      '对比',
      'diff',
      'schema',
      '校验',
      'typescript',
      'ts',
      'interface',
      '美化',
      'format',
      'validate',
    ],
    categoryId: 'dev',
    icon: '📋',
    type: 'window',
    windowLabel: 'tool-json',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'regex',
    name: '正则表达式',
    description: '正则测试、高亮匹配、替换、常用模板库、分组捕获',
    keywords: [
      'regex',
      'regexp',
      '正则',
      '正则表达式',
      '匹配',
      '测试',
      '替换',
      '模板',
      'pattern',
      'match',
    ],
    categoryId: 'dev',
    icon: '🔍',
    type: 'window',
    windowLabel: 'tool-regex',
    windowWidth: 1400,
    windowHeight: 900,
  },
  {
    id: 'random',
    name: '随机生成器',
    description: 'UUID、NanoID、密码、Token、API Key、JWT Secret、Snowflake ID、随机数',
    keywords: [
      'uuid',
      'guid',
      'nanoid',
      'ulid',
      'snowflake',
      '随机',
      '密码',
      'password',
      'token',
      'api key',
      'jwt',
      'secret',
      'hash',
      '生成',
      'random',
    ],
    categoryId: 'dev',
    icon: '🎲',
    type: 'window',
    windowLabel: 'tool-random',
    windowWidth: 1100,
    windowHeight: 850,
  },
  // ── 高频实用工具 ──────────────────────────────────────────────────────────
  {
    id: 'timestamp',
    name: '时间戳转换',
    description: 'Unix 时间戳与日期时间互转，支持秒/毫秒，多种格式输出',
    keywords: ['时间戳', 'timestamp', 'unix', '日期', '时间', '转换', 'epoch', 'date', 'time'],
    categoryId: 'dev',
    icon: '⏱️',
    type: 'window',
    windowLabel: 'tool-timestamp',
    windowWidth: 680,
    windowHeight: 700,
  },
  {
    id: 'hash',
    name: 'Hash 计算',
    description: '文本/文件哈希计算，支持 SHA-1、SHA-256、SHA-384、SHA-512，哈希对比验证',
    keywords: [
      'hash',
      'sha',
      'sha256',
      'sha512',
      'md5',
      '哈希',
      '摘要',
      '校验',
      '加密',
      '文件校验',
    ],
    categoryId: 'dev',
    icon: '#️⃣',
    type: 'window',
    windowLabel: 'tool-hash',
    windowWidth: 680,
    windowHeight: 700,
  },
  {
    id: 'jwt',
    name: 'JWT 解析',
    description: '解析 JWT Token 的 Header、Payload、Signature，显示过期时间',
    keywords: [
      'jwt',
      'token',
      '解析',
      'decode',
      'header',
      'payload',
      'signature',
      '过期',
      'bearer',
    ],
    categoryId: 'dev',
    icon: '🔑',
    type: 'window',
    windowLabel: 'tool-jwt',
    windowWidth: 680,
    windowHeight: 700,
  },
  {
    id: 'http-client',
    name: 'HTTP 请求',
    description: '发送 HTTP 请求，支持 GET/POST/PUT/DELETE 等方法，查看响应',
    keywords: [
      'http',
      'request',
      'api',
      'get',
      'post',
      'put',
      'delete',
      'rest',
      'curl',
      'postman',
      '接口测试',
    ],
    categoryId: 'network',
    icon: '🌐',
    type: 'window',
    windowLabel: 'tool-http-client',
    windowWidth: 1000,
    windowHeight: 750,
  },
  {
    id: 'cron',
    name: 'Cron 表达式',
    description: '解析 Cron 表达式为人类可读描述，显示下次执行时间',
    keywords: ['cron', '定时', '表达式', '任务', 'schedule', '执行时间', 'job'],
    categoryId: 'dev',
    icon: '⏰',
    type: 'window',
    windowLabel: 'tool-cron',
    windowWidth: 700,
    windowHeight: 700,
  },
  {
    id: 'sql',
    name: 'SQL 格式化',
    description: 'SQL 美化/压缩，支持 MySQL/PostgreSQL/SQLite/BigQuery 等 7 种方言',
    keywords: [
      'sql',
      '格式化',
      '美化',
      '压缩',
      'mysql',
      'postgresql',
      'sqlite',
      'database',
      '数据库',
    ],
    categoryId: 'dev',
    icon: '🗄️',
    type: 'window',
    windowLabel: 'tool-sql',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'database-manager',
    name: '数据库管理',
    description: '管理 PostgreSQL、MySQL、SQLite、Redis、MongoDB 连接，浏览对象并运行查询',
    keywords: [
      'database',
      'db',
      'navicat',
      'mysql',
      'postgresql',
      'sqlite',
      'redis',
      'mongodb',
      'mongo',
      'sql',
      '数据库',
      '查询',
      '数据表',
      'collection',
      'key',
    ],
    categoryId: 'dev',
    icon: '🧭',
    type: 'window',
    windowLabel: 'tool-database-manager',
    windowWidth: 1480,
    windowHeight: 900,
  },
  {
    id: 'code-formatter',
    name: '代码格式化',
    description: '基于 Prettier，支持 JS/TS/CSS/HTML/JSON/YAML/Markdown 格式化',
    keywords: [
      'prettier',
      '格式化',
      'format',
      'javascript',
      'typescript',
      'css',
      'html',
      'json',
      'yaml',
      'markdown',
      '代码',
    ],
    categoryId: 'dev',
    icon: '✨',
    type: 'window',
    windowLabel: 'tool-code-formatter',
    windowWidth: 1200,
    windowHeight: 800,
  },
  {
    id: 'github-store',
    name: 'GitHub Store',
    description: 'GitHub 项目发现、Release 资产浏览、收藏和每日更新日榜',
    keywords: [
      'github',
      'store',
      'release',
      'repository',
      'repo',
      '仓库',
      '开源',
      '日榜',
      '趋势',
      'trending',
      'developer',
      '开发工具',
    ],
    categoryId: 'dev',
    icon: '🧭',
    type: 'window',
    windowLabel: 'tool-github-store',
    windowWidth: 1440,
    windowHeight: 860,
  },
  {
    id: 'web-check',
    name: 'Web Check 网站体检',
    description: '聚合 HTTP、DNS、安全头、Cookie、端口、页面元数据和技术栈信号的网站体检工具',
    keywords: [
      'web check',
      'web-check',
      '网站体检',
      '网站安全',
      'security headers',
      'headers',
      'cookie',
      'dns',
      'robots',
      'sitemap',
      'osint',
      '开发工具',
    ],
    categoryId: 'dev',
    icon: '🩺',
    type: 'window',
    windowLabel: 'tool-web-check',
    windowWidth: 1440,
    windowHeight: 900,
  },
  // ── 图片处理工具 ──────────────────────────────────────────────────────────
  {
    id: 'image-compress',
    name: '图片压缩',
    description: '压缩 PNG/JPEG/WebP 图片，调整质量，减小文件体积',
    keywords: ['图片', '压缩', 'compress', 'png', 'jpeg', 'webp', '体积', '质量', 'image'],
    categoryId: 'image',
    icon: '📦',
    type: 'window',
    windowLabel: 'tool-image-compress',
    windowWidth: 900,
    windowHeight: 700,
  },
  {
    id: 'image-batch-process',
    name: '图片批量处理',
    description: '工作流式批量裁剪、尺寸调整、翻转镜像、水印和格式转换，适合照片/电商/素材整理',
    keywords: [
      '图片',
      '批量处理',
      '批量裁剪',
      '批量缩放',
      '批量水印',
      '格式转换',
      '工作流',
      '光影魔术手',
      '裁剪',
      '尺寸',
      '翻转',
      '镜像',
      'watermark',
      'resize',
      'crop',
      'batch',
    ],
    categoryId: 'image',
    icon: '🧰',
    type: 'window',
    windowLabel: 'tool-image-batch-process',
    windowWidth: 1360,
    windowHeight: 860,
  },
  {
    id: 'image-crop',
    name: '图片裁剪',
    description: '自由裁剪图片，支持自定义区域和预设比例',
    keywords: ['图片', '裁剪', 'crop', '剪切', '截取', '区域', 'image'],
    categoryId: 'image',
    icon: '✂️',
    type: 'window',
    windowLabel: 'tool-image-crop',
    windowWidth: 1000,
    windowHeight: 750,
  },
  {
    id: 'image-resize',
    name: '图片尺寸调整',
    description: '调整图片宽高尺寸，支持等比缩放和自定义尺寸',
    keywords: ['图片', '尺寸', '大小', 'resize', '缩放', '宽', '高', 'scale', 'image'],
    categoryId: 'image',
    icon: '📐',
    type: 'window',
    windowLabel: 'tool-image-resize',
    windowWidth: 900,
    windowHeight: 700,
  },
  {
    id: 'image-transform',
    name: '图片旋转翻转',
    description: '旋转 90°/180°/270°，左右镜像，上下翻转',
    keywords: ['图片', '旋转', '翻转', '镜像', 'rotate', 'flip', 'mirror', '左右', '上下', 'image'],
    categoryId: 'image',
    icon: '🔄',
    type: 'window',
    windowLabel: 'tool-image-transform',
    windowWidth: 900,
    windowHeight: 700,
  },
  {
    id: 'image-filter',
    name: '图片滤镜',
    description: '灰度、反色、亮度、对比度、模糊、锐化、色相旋转',
    keywords: ['图片', '滤镜', 'filter', '灰度', '反色', '亮度', '对比度', '模糊', '锐化', 'image'],
    categoryId: 'image',
    icon: '🎨',
    type: 'window',
    windowLabel: 'tool-image-filter',
    windowWidth: 1000,
    windowHeight: 750,
  },
  {
    id: 'image-watermark',
    name: '图片水印',
    description: '文字/图片水印，支持角度、间距、透明度、平铺、位置等全参数',
    keywords: ['图片', '水印', 'watermark', '文字', '版权', '标注', '平铺', 'image'],
    categoryId: 'image',
    icon: '🔏',
    type: 'window',
    windowLabel: 'tool-image-watermark',
    windowWidth: 1100,
    windowHeight: 780,
  },
  {
    id: 'image-exif',
    name: 'EXIF 查看修改',
    description: '查看并修改图片 EXIF 元数据，支持相机、作者、版权、GPS 与隐私字段处理',
    keywords: ['exif', '元数据', 'metadata', 'gps', '相机', '拍摄', '隐私', '图片信息', '修改'],
    categoryId: 'image',
    icon: '🔎',
    type: 'window',
    windowLabel: 'tool-image-exif',
    windowWidth: 1120,
    windowHeight: 780,
  },
  {
    id: 'image-convert',
    name: '图片格式转换',
    description: '批量转换图片格式：PNG/JPEG/WebP/BMP/TIFF/ICO 互转',
    keywords: ['图片', '格式', '转换', 'convert', 'png', 'jpeg', 'webp', 'bmp', 'tiff', 'ico'],
    categoryId: 'image',
    icon: '🔁',
    type: 'window',
    windowLabel: 'tool-image-convert',
    windowWidth: 900,
    windowHeight: 700,
  },
  {
    id: 'image-ico-generator',
    name: 'ICO 生成器',
    description:
      '图片或文字批量生成 Windows ICO 图标，支持多尺寸图层、透明/RGB、字体渲染和 ZIP 打包',
    keywords: [
      'ico',
      'icon',
      'favicon',
      '图标',
      '文字图标',
      '字体图标',
      '生成器',
      '批量',
      '透明',
      'zip',
      'windows',
      'app icon',
      'text icon',
      'favicon.ico',
    ],
    categoryId: 'image',
    icon: '🧩',
    type: 'window',
    windowLabel: 'tool-image-ico-generator',
    windowWidth: 1180,
    windowHeight: 820,
  },
  {
    id: 'image-bg-remove',
    name: 'AI 智能抠图',
    description:
      '基于 BiRefNet AI 模型，本地推理，发丝级精度，支持人像/物体/复杂背景，首次使用需下载模型',
    keywords: [
      '抠图',
      '去背景',
      'background',
      'remove',
      'ai',
      '人像',
      '透明',
      'png',
      'birefnet',
      '智能',
    ],
    categoryId: 'image',
    icon: '✂️',
    type: 'window',
    windowLabel: 'tool-image-bg-remove',
    windowWidth: 1000,
    windowHeight: 720,
  },
  {
    id: 'image-ai-upscale',
    name: 'AI 图像放大增强',
    description:
      '基于 Real-ESRGAN NCNN/Vulkan，本地 GPU 超分辨率放大，支持通用照片、动漫插画和批量增强',
    keywords: [
      '放大',
      '增强',
      '超分',
      '超分辨率',
      'upscale',
      'realesrgan',
      'real-esrgan',
      'ncnn',
      'vulkan',
      'ai',
      '清晰',
      '高清',
      '图片修复',
    ],
    categoryId: 'image',
    icon: '🔍',
    type: 'window',
    windowLabel: 'tool-image-ai-upscale',
    windowWidth: 1180,
    windowHeight: 780,
  },
  {
    id: 'image-watermark-remove',
    name: 'AI 智能去水印',
    description:
      '支持智能自动和手动标注两种模式，本地后端推理，适合处理常见角标、文字水印和复杂遮挡区域',
    keywords: [
      '去水印',
      'watermark',
      'remove',
      'ai',
      '自动去水印',
      '手动标注',
      '修复',
      'inpaint',
      'lama',
      '清除水印',
    ],
    categoryId: 'image',
    icon: '🧼',
    type: 'window',
    windowLabel: 'tool-image-watermark-remove',
    windowWidth: 1180,
    windowHeight: 780,
  },
  {
    id: 'image-magic-eraser',
    name: 'AI 智能擦除',
    description: '魔法橡皮擦，涂抹删除人物、物体、文字和杂物，基于 LaMa 本地修复模型自动补背景',
    keywords: [
      '智能擦除',
      '魔法橡皮擦',
      '物体移除',
      '人物移除',
      '删除物体',
      '去杂物',
      'erase',
      'eraser',
      'lama',
      'inpaint',
      'ai',
      '修复',
      '补背景',
    ],
    categoryId: 'image',
    icon: '🪄',
    type: 'window',
    windowLabel: 'tool-image-magic-eraser',
    windowWidth: 1180,
    windowHeight: 780,
  },
  // ── 下载工具 ──────────────────────────────────────────────────────────
  {
    id: 'download-manager',
    name: '多线程下载器',
    description:
      '独立下载管理器，支持批量链接、HTTP 多线程、m3u8/HLS、FTP、磁力/BT、Metalink 和 aria2 协议任务',
    keywords: [
      '下载器',
      '下载管理',
      '多线程下载',
      '批量下载',
      '断点续传',
      'm3u8',
      'HLS',
      'FTP',
      '磁力',
      'BT',
      'magnet',
      'torrent',
      'Metalink',
      'meta4',
      'aria2',
      'aria2c',
      'IDM',
      'Gopeed',
      'HTTP下载',
      'HTTPS下载',
      'download manager',
      'multi thread download',
    ],
    categoryId: 'download',
    icon: '📥',
    type: 'window',
    windowLabel: 'tool-download-manager',
    windowWidth: 1280,
    windowHeight: 820,
  },
  {
    id: 'video-downloader',
    name: '视频下载',
    description: '基于 yt-dlp 下载网页视频、音频和字幕，支持格式解析、Cookie 登录态和进度显示',
    keywords: [
      '视频下载',
      '下载',
      'yt-dlp',
      'youtube-dl',
      'youtube',
      'bilibili',
      'b站',
      '抖音',
      '小红书',
      '音频下载',
      '字幕下载',
      'download',
      'video downloader',
    ],
    categoryId: 'download',
    icon: '⬇️',
    type: 'window',
    windowLabel: 'tool-video-downloader',
    windowWidth: 1280,
    windowHeight: 820,
  },
  {
    id: 'tikhub-downloader',
    name: 'TikHub 下载',
    description: '基于 TikHub 原生接口下载多平台视频，独立配置 API Key、解析信息和下载进度',
    keywords: [
      'TikHub',
      '抖音下载',
      'TikTok下载',
      '小红书下载',
      '快手下载',
      'B站下载',
      'YouTube下载',
      '微博下载',
      '短视频下载',
      'douyin',
      'tiktok',
      'xiaohongshu',
      'kuaishou',
      'bilibili',
      'youtube',
      'weibo',
      'api key',
      '下载',
      'download',
    ],
    categoryId: 'download',
    icon: '⚡',
    type: 'window',
    windowLabel: 'tool-tikhub-downloader',
    windowWidth: 1280,
    windowHeight: 820,
  },
  {
    id: 'douyin-downloader',
    name: '抖音下载',
    description: '自研解析抖音公开分享页，支持分享文案识别、两种播放版本、预览和进度下载',
    keywords: [
      '抖音下载',
      '抖音',
      'douyin',
      '短视频',
      '分享链接',
      '视频下载',
      '公开分享页',
      'download',
    ],
    categoryId: 'download',
    icon: '🎵',
    type: 'window',
    windowLabel: 'tool-douyin-downloader',
    windowWidth: 1280,
    windowHeight: 820,
  },
  {
    id: 'wx-channels-downloader',
    name: '微信视频任务管理',
    description: '微信 PC 视频号捕获、作品解析、清晰度选择和下载任务统一管理',
    keywords: [
      '微信视频下载',
      '微信视频号',
      '视频号下载',
      'wechat',
      'wx_channels_download',
      '微信',
      '视频下载',
      '下载',
      '代理',
      '证书',
    ],
    categoryId: 'download',
    icon: '💬',
    type: 'window',
    windowLabel: 'tool-wx-channels-downloader',
    windowWidth: 1280,
    windowHeight: 820,
  },
  // ── 音视频工具 ──────────────────────────────────────────────────────────
  {
    id: 'video-player',
    name: '视频播放器',
    description:
      '本地和网络视频播放，支持播放列表、拖拽导入、倍速、循环、全屏、画中画和系统打开方式',
    keywords: [
      '视频播放器',
      '播放器',
      '播放',
      'video',
      'player',
      'screenbox',
      'mp4',
      'webm',
      'mov',
      'mkv',
      'avi',
      '全屏',
      '画中画',
      '倍速',
      '播放列表',
    ],
    categoryId: 'media',
    icon: '🎥',
    type: 'window',
    windowLabel: 'tool-video-player',
    windowWidth: 1280,
    windowHeight: 780,
  },
  {
    id: 'music-player',
    name: '音乐播放器',
    description: '本地和网络音乐播放，支持播放队列、搜索、倍速、循环和系统打开方式',
    keywords: [
      '音乐播放器',
      '音频播放器',
      '播放器',
      '音乐',
      '歌曲',
      'music',
      'audio',
      'player',
      'feishin',
      'mp3',
      'flac',
      'wav',
      'm4a',
      'ogg',
      'opus',
      '播放列表',
      '队列',
    ],
    categoryId: 'media',
    icon: '🎵',
    type: 'window',
    windowLabel: 'tool-music-player',
    windowWidth: 1220,
    windowHeight: 780,
  },
  {
    id: 'video-convert',
    name: '视频格式转换',
    description:
      '视频格式互转、压缩、调整分辨率/帧率/码率，支持 MP4/MKV/AVI/MOV/WebM/GIF 等，调用系统 FFmpeg',
    keywords: [
      '视频',
      '转换',
      '格式',
      'ffmpeg',
      'mp4',
      'mkv',
      'avi',
      'mov',
      'webm',
      'flv',
      'wmv',
      'gif',
      '压缩',
      '分辨率',
      '帧率',
      'video',
      'convert',
    ],
    categoryId: 'media',
    icon: '🎬',
    type: 'window',
    windowLabel: 'tool-video-convert',
    windowWidth: 960,
    windowHeight: 700,
  },
  {
    id: 'audio-convert',
    name: '音频格式转换',
    description:
      '音频格式互转、调整码率/采样率，支持 MP3/WAV/FLAC/AAC/OGG/M4A/WMA/OPUS，调用系统 FFmpeg',
    keywords: [
      '音频',
      '转换',
      '格式',
      'ffmpeg',
      'mp3',
      'wav',
      'flac',
      'aac',
      'ogg',
      'm4a',
      'wma',
      'opus',
      '码率',
      '采样率',
      'audio',
      'convert',
    ],
    categoryId: 'media',
    icon: '🎵',
    type: 'window',
    windowLabel: 'tool-audio-convert',
    windowWidth: 860,
    windowHeight: 650,
  },
  {
    id: 'video-compress',
    name: '视频压缩',
    description:
      '视频压缩减小体积，预设高质量/均衡/小文件/极小/H.265方案，支持自定义 CRF/编码/分辨率/帧率',
    keywords: [
      '视频',
      '压缩',
      'compress',
      'mp4',
      'mkv',
      'crf',
      'h264',
      'h265',
      'hevc',
      '码率',
      '分辨率',
      '体积',
      'ffmpeg',
      'video',
    ],
    categoryId: 'media',
    icon: '📦',
    type: 'window',
    windowLabel: 'tool-video-compress',
    windowWidth: 900,
    windowHeight: 680,
  },
  {
    id: 'audio-compress',
    name: '音频压缩',
    description:
      '音频压缩减小体积，预设无损/高质量/标准/小文件/语音方案，支持自定义编码/码率/采样率',
    keywords: [
      '音频',
      '压缩',
      'compress',
      'mp3',
      'aac',
      'flac',
      'opus',
      '码率',
      '采样率',
      '体积',
      'ffmpeg',
      'audio',
    ],
    categoryId: 'media',
    icon: '🎙️',
    type: 'window',
    windowLabel: 'tool-audio-compress',
    windowWidth: 860,
    windowHeight: 620,
  },
  {
    id: 'video-split',
    name: '视频音频分离',
    description: '从视频中分离视频轨和音频轨，流复制零损失，支持批量处理，可单独提取视频或音频',
    keywords: [
      '分离',
      '提取',
      '视频',
      '音频',
      'split',
      'extract',
      'demux',
      '视频轨',
      '音频轨',
      'ffmpeg',
      'mp4',
      'mkv',
    ],
    categoryId: 'media',
    icon: '✂️',
    type: 'window',
    windowLabel: 'tool-video-split',
    windowWidth: 860,
    windowHeight: 620,
  },
  {
    id: 'video-watermark-remove',
    name: 'AI 去除视频水印',
    description:
      '本地处理视频水印，支持 FFmpeg 固定区域快速去除和 ProPainter AI 视频修复模式，可保留音频并输出 MP4/MKV/MOV',
    keywords: [
      '视频去水印',
      '去水印',
      '视频',
      'watermark',
      'remove',
      'delogo',
      'propainter',
      'inpaint',
      'ai',
      'logo',
      '字幕',
      '修复',
      'ffmpeg',
    ],
    categoryId: 'media',
    icon: '🎞️',
    type: 'window',
    windowLabel: 'tool-video-watermark-remove',
    windowWidth: 1180,
    windowHeight: 780,
  },
  {
    id: 'local-speech-to-text',
    name: '本地语音转文字',
    description: '基于 sherpa-onnx 和 SenseVoice，在本机离线识别音频/视频中的语音文本',
    keywords: [
      '语音转文字',
      '语音识别',
      '转写',
      '字幕',
      'asr',
      'stt',
      'sherpa-onnx',
      'SenseVoice',
      '离线识别',
      '音频',
      '视频',
      'media',
    ],
    categoryId: 'media',
    icon: '🎙️',
    type: 'window',
    windowLabel: 'tool-local-speech-to-text',
    windowWidth: 1180,
    windowHeight: 820,
  },
  {
    id: 'local-text-to-speech',
    name: '本地文字转语音 TTS',
    description: '基于 sherpa-onnx 和 Kokoro，在本机离线将文本合成为 WAV 语音',
    keywords: [
      '文字转语音',
      '语音合成',
      'tts',
      'Kokoro',
      'sherpa-onnx',
      '离线合成',
      '朗读',
      '音色',
      '音频',
      'media',
    ],
    categoryId: 'media',
    icon: '🗣️',
    type: 'window',
    windowLabel: 'tool-local-text-to-speech',
    windowWidth: 1180,
    windowHeight: 820,
  },
  {
    id: 'local-speech-denoise',
    name: '本地语音增强 / 降噪',
    description: '基于 sherpa-onnx 和 DPDFNet，本机离线降低语音背景噪声并输出 WAV',
    keywords: [
      '语音增强',
      '降噪',
      '噪声',
      'denoise',
      'speech enhancement',
      'DPDFNet',
      'sherpa-onnx',
      '离线处理',
      '音频',
      'media',
    ],
    categoryId: 'media',
    icon: '🔊',
    type: 'window',
    windowLabel: 'tool-local-speech-denoise',
    windowWidth: 1180,
    windowHeight: 820,
  },
  {
    id: 'local-vocal-separation',
    name: '本地人声 / 伴奏分离',
    description: '基于 sherpa-onnx 和 Spleeter 2-stem，本机离线分离人声与伴奏',
    keywords: [
      '人声分离',
      '伴奏分离',
      '音源分离',
      'source separation',
      'spleeter',
      'vocal',
      '伴奏',
      'sherpa-onnx',
      '离线处理',
      '音频',
      'media',
    ],
    categoryId: 'media',
    icon: '🎚️',
    type: 'window',
    windowLabel: 'tool-local-vocal-separation',
    windowWidth: 1180,
    windowHeight: 820,
  },
  {
    id: 'screen-recording',
    name: '屏幕录制',
    description: '录制全屏、自定义区域或指定软件窗口，调用系统 FFmpeg 输出 MP4/WebM/MKV/MOV',
    keywords: [
      '屏幕录制',
      '录屏',
      '录制',
      '全屏录制',
      '区域录制',
      '窗口录制',
      'screen',
      'record',
      'recorder',
      'ffmpeg',
      'mp4',
      'webm',
    ],
    categoryId: 'efficiency',
    icon: '⏺',
    type: 'window',
    windowLabel: 'tool-screen-recording',
    windowWidth: 1040,
    windowHeight: 720,
  },
  {
    id: 'gif-recorder',
    name: 'GIF 小工具',
    description: '框选屏幕区域录制操作过程，直接保存为 GIF 动图',
    keywords: ['gif', '动图', '录制gif', '屏幕gif', '区域录制', '录屏', 'screen gif', 'record gif'],
    categoryId: 'efficiency',
    icon: '🎞️',
    type: 'window',
    windowLabel: 'tool-gif-recorder',
    windowWidth: 520,
    windowHeight: 360,
  },
  // ── PDF 工具 ──────────────────────────────────────────────────────────
  {
    id: 'pdf-merge',
    name: 'PDF 合并',
    description: '将多个 PDF 文件合并为一个，支持拖拽排序',
    keywords: ['pdf', '合并', 'merge', '合并pdf', 'combine'],
    categoryId: 'pdf',
    icon: '📎',
    type: 'window',
    windowLabel: 'tool-pdf-merge',
    windowWidth: 860,
    windowHeight: 640,
  },
  {
    id: 'pdf-split',
    name: 'PDF 拆分',
    description: '按页码范围拆分 PDF，支持提取指定页面或每页单独保存',
    keywords: ['pdf', '拆分', 'split', '分割', '提取页面'],
    categoryId: 'pdf',
    icon: '✂️',
    type: 'window',
    windowLabel: 'tool-pdf-split',
    windowWidth: 860,
    windowHeight: 640,
  },
  {
    id: 'pdf-rotate',
    name: 'PDF 旋转',
    description: '旋转 PDF 页面，支持 90°/180°/270°，可选择全部或指定页面',
    keywords: ['pdf', '旋转', 'rotate', '翻转', '方向'],
    categoryId: 'pdf',
    icon: '🔄',
    type: 'window',
    windowLabel: 'tool-pdf-rotate',
    windowWidth: 860,
    windowHeight: 640,
  },
  {
    id: 'pdf-encrypt',
    name: 'PDF 加密/解密',
    description: '为 PDF 设置密码保护，或移除已有密码',
    keywords: ['pdf', '加密', '解密', '密码', 'encrypt', 'decrypt', 'password', '保护'],
    categoryId: 'pdf',
    icon: '🔐',
    type: 'window',
    windowLabel: 'tool-pdf-encrypt',
    windowWidth: 780,
    windowHeight: 560,
  },
  {
    id: 'pdf-watermark',
    name: 'PDF 水印',
    description: '为 PDF 添加文字或图片水印，支持透明度、角度、位置设置',
    keywords: ['pdf', '水印', 'watermark', '文字', '版权', '标注'],
    categoryId: 'pdf',
    icon: '💧',
    type: 'window',
    windowLabel: 'tool-pdf-watermark',
    windowWidth: 900,
    windowHeight: 680,
  },
  {
    id: 'pdf-compress',
    name: 'PDF 压缩',
    description: '压缩 PDF 文件体积，需要安装 Ghostscript',
    keywords: ['pdf', '压缩', 'compress', '减小', '体积', 'ghostscript'],
    categoryId: 'pdf',
    icon: '📦',
    type: 'window',
    windowLabel: 'tool-pdf-compress',
    windowWidth: 860,
    windowHeight: 600,
  },
  {
    id: 'pdf-to-image',
    name: 'PDF 转图片',
    description: 'PDF 每页转换为 PNG/JPG 图片，需要安装 Ghostscript',
    keywords: ['pdf', '转图片', 'to image', 'png', 'jpg', 'ghostscript', '导出'],
    categoryId: 'pdf',
    icon: '🖼️',
    type: 'window',
    windowLabel: 'tool-pdf-to-image',
    windowWidth: 860,
    windowHeight: 620,
  },
  {
    id: 'image-to-pdf',
    name: '图片转 PDF',
    description: '将多张图片（PNG/JPG/WebP）合并转换为 PDF 文件',
    keywords: ['图片', '转pdf', 'image to pdf', 'png', 'jpg', '合并', '转换'],
    categoryId: 'pdf',
    icon: '📄',
    type: 'window',
    windowLabel: 'tool-image-to-pdf',
    windowWidth: 860,
    windowHeight: 640,
  },
  {
    id: 'pdf-delete-pages',
    name: 'PDF 删除页面',
    description: '删除 PDF 中指定页面，支持多选、范围选择',
    keywords: ['pdf', '删除', '页面', 'delete', 'remove', '去除', '页码'],
    categoryId: 'pdf',
    icon: '🗑️',
    type: 'window',
    windowLabel: 'tool-pdf-delete-pages',
    windowWidth: 960,
    windowHeight: 680,
  },
  {
    id: 'pdf-translate',
    name: 'AI PDF 格式翻译',
    description: '按页面原始版式翻译 PDF，支持文字型 PDF 和扫描件 OCR 翻译',
    keywords: [
      'pdf',
      '翻译',
      '格式翻译',
      '版式',
      'ocr',
      '扫描件',
      'translate',
      'translation',
      'ai',
      '双语',
    ],
    categoryId: 'pdf',
    icon: '🌐',
    type: 'window',
    windowLabel: 'tool-pdf-translate',
    windowWidth: 1180,
    windowHeight: 780,
  },
  {
    id: 'excel-preview',
    name: 'Excel 预览',
    description: '无需安装 Office，本地预览 Excel/CSV，多 sheet 浏览并支持查看单元格公式',
    keywords: ['excel', '预览', '查看', 'sheet', '公式', 'xlsx', 'xls', 'csv', '工作表'],
    categoryId: 'office',
    icon: '👀',
    type: 'window',
    windowLabel: 'tool-excel-preview',
    windowWidth: 1280,
    windowHeight: 840,
  },
  {
    id: 'excel-formula-to-value',
    name: 'Excel公式转值',
    description: '将工作簿中的所有公式转换为静态结果值，适合归档、汇报和数据固化',
    keywords: ['excel', '公式', '转值', '公式转值', '静态值', 'value', 'formula', '固化'],
    categoryId: 'office',
    icon: '🧮',
    type: 'window',
    windowLabel: 'tool-excel-formula-to-value',
    windowWidth: 860,
    windowHeight: 700,
  },
  {
    id: 'excel-remove-duplicates',
    name: 'Excel重复列数据移除',
    description: '按指定列去重，支持保留第一个、保留最后一个和全部移除三种模式',
    keywords: ['excel', '去重', '重复', '重复列', 'duplicate', 'dedup', '字段去重', '按列去重'],
    categoryId: 'office',
    icon: '🧽',
    type: 'window',
    windowLabel: 'tool-excel-remove-duplicates',
    windowWidth: 920,
    windowHeight: 760,
  },
  {
    id: 'excel-merge',
    name: 'Excel 合并',
    description: '合并多个 Excel 文件为一个表格，默认首行为表头',
    keywords: ['excel', '合并', 'merge', 'xlsx', '表格', '汇总'],
    categoryId: 'office',
    icon: '📊',
    type: 'window',
    windowLabel: 'tool-excel-merge',
    windowWidth: 860,
    windowHeight: 640,
  },
  {
    id: 'excel-split',
    name: 'Excel 拆分',
    description: '按指定的列（如部门、城市等）将一个表格拆分为多个独立文件',
    keywords: ['excel', '拆分', 'split', 'xlsx', '表格', '分组'],
    categoryId: 'office',
    icon: '✂️',
    type: 'window',
    windowLabel: 'tool-excel-split',
    windowWidth: 860,
    windowHeight: 640,
  },
  {
    id: 'excel-diff',
    name: 'Excel 数据对比',
    description: '智能比对两份 Excel 的数据差异（新增、删除、修改）并高亮导出',
    keywords: ['excel', '对比', 'diff', '差异', '比对', '核对'],
    categoryId: 'office',
    icon: '⚖️',
    type: 'window',
    windowLabel: 'tool-excel-diff',
    windowWidth: 860,
    windowHeight: 640,
  },
  {
    id: 'excel-convert',
    name: '乱码修复与转换',
    description: '智能修复乱码 CSV，支持批量与 Excel 格式无损互转',
    keywords: ['excel', 'csv', '转换', '乱码', '修复', '互转', '格式'],
    categoryId: 'office',
    icon: '🔄',
    type: 'window',
    windowLabel: 'tool-excel-convert',
    windowWidth: 860,
    windowHeight: 640,
  },
  {
    id: 'excel-remove-empty',
    name: 'Excel 删除空行',
    description: '自动识别并删除 Excel 中所有没有数据的空行，提高数据整洁度',
    keywords: ['excel', '空行', '删除', '清理', 'empty', 'rows'],
    categoryId: 'office',
    icon: '🧹',
    type: 'window',
    windowLabel: 'tool-excel-remove-empty',
    windowWidth: 860,
    windowHeight: 640,
  },
  {
    id: 'md-word-convert',
    name: 'Markdown / Word 互转',
    description: 'Markdown 与 DOCX 双向转换，首次使用按需下载 Pandoc，本地缓存后可重复使用',
    keywords: ['markdown', 'md', 'word', 'docx', '转换', '互转', 'pandoc', '文档转换', 'office'],
    categoryId: 'office',
    icon: '🧾',
    type: 'window',
    windowLabel: 'tool-md-word-convert',
    windowWidth: 1120,
    windowHeight: 780,
  },
  {
    id: 'file-to-markdown',
    name: '文件转 Markdown',
    description: '使用 Microsoft MarkItDown 将 PDF、Office、网页、表格、图片等文件转换为 Markdown',
    keywords: [
      'markdown',
      'md',
      'markitdown',
      'microsoft',
      'pdf',
      'word',
      'docx',
      'ppt',
      'pptx',
      'excel',
      'xlsx',
      'html',
      'csv',
      'json',
      '图片',
      '文件转换',
      '文档转换',
      '转markdown',
      'office',
    ],
    categoryId: 'office',
    icon: '📝',
    type: 'window',
    windowLabel: 'tool-file-to-markdown',
    windowWidth: 1120,
    windowHeight: 820,
  },
  {
    id: 'pdf-word-ocr',
    name: 'PDF 转 Word',
    description: '使用内置 PaddleOCR 将扫描件 PDF 转为可编辑 Word 文本文档',
    keywords: [
      'pdf',
      'word',
      'docx',
      'ocr',
      'PaddleOCR',
      '扫描件',
      '图片型PDF',
      '转word',
      '文档转换',
      'office',
    ],
    categoryId: 'office',
    icon: '📄',
    type: 'window',
    windowLabel: 'tool-pdf-word-ocr',
    windowWidth: 1120,
    windowHeight: 780,
  },
  {
    id: 'tencent-table-ocr',
    name: '腾讯云 OCR 表格识别',
    description: '调用腾讯云表格识别 V3，识别图片、PDF 或剪贴板图片中的表格并导出 Excel',
    keywords: [
      '腾讯云',
      '腾讯',
      'ocr',
      'pdf',
      'PDF表格',
      '表格识别',
      '高精度表格',
      'RecognizeTableAccurateOCR',
      '图片转表格',
      '图片转Excel',
      'PDF转Excel',
      '粘贴图片',
      '剪贴板图片',
      'excel',
      'xlsx',
      'office',
    ],
    categoryId: 'office',
    icon: '📊',
    type: 'window',
    windowLabel: 'tool-tencent-table-ocr',
    windowWidth: 1120,
    windowHeight: 780,
  },
  {
    id: 'tencent-bank-card-ocr',
    name: '腾讯云 OCR 银行卡识别',
    description: '调用腾讯云 BankCardOCR，识别银行卡卡号、银行、有效期、卡类型和风险告警',
    keywords: [
      '腾讯云',
      '腾讯',
      'ocr',
      '银行卡',
      '银行卡识别',
      'BankCardOCR',
      '卡号识别',
      '银行',
      '有效期',
      '信用卡',
      '借记卡',
      '粘贴图片',
      '剪贴板图片',
      'office',
    ],
    categoryId: 'office',
    icon: '💳',
    type: 'window',
    windowLabel: 'tool-tencent-bank-card-ocr',
    windowWidth: 1120,
    windowHeight: 780,
  },
  {
    id: 'tencent-general-invoice-ocr',
    name: '腾讯云 OCR 通用票据识别',
    description: '调用腾讯云通用票据识别高级版 RecognizeGeneralInvoice，识别图片、PDF 或剪贴板票据',
    keywords: [
      '腾讯云',
      '腾讯',
      'ocr',
      '通用票据',
      '票据识别',
      'RecognizeGeneralInvoice',
      '发票',
      'invoice',
      'PDF票据',
      '增值税发票',
      '全电发票',
      '火车票',
      '机票',
      '出租车票',
      '通行费',
      '银行回单',
      '购物小票',
      '粘贴图片',
      '剪贴板图片',
      'office',
    ],
    categoryId: 'office',
    icon: '🧾',
    type: 'window',
    windowLabel: 'tool-tencent-general-invoice-ocr',
    windowWidth: 1180,
    windowHeight: 820,
  },
  {
    id: 'md-ppt-convert',
    name: 'Markdown 转 PPT',
    description: '将 Markdown 快速生成 PPTX，可选择 reference.pptx 套用演示模板',
    keywords: ['markdown', 'md', 'ppt', 'pptx', '幻灯片', '演示', '汇报', 'pandoc', 'office'],
    categoryId: 'office',
    icon: '📽️',
    type: 'window',
    windowLabel: 'tool-md-ppt-convert',
    windowWidth: 1120,
    windowHeight: 780,
  },
  {
    id: 'epub-generator',
    name: 'EPUB 电子书生成器',
    description: '将 Markdown、DOCX、HTML 或 TXT 转成 EPUB，支持封面、作者、目录和 CSS',
    keywords: [
      'epub',
      '电子书',
      'ebook',
      'markdown',
      'docx',
      'html',
      'txt',
      '书籍',
      '手册',
      'pandoc',
      'office',
    ],
    categoryId: 'office',
    icon: '📚',
    type: 'window',
    windowLabel: 'tool-epub-generator',
    windowWidth: 1120,
    windowHeight: 820,
  },
  {
    id: 'draw-stamp',
    name: '电子印章制作',
    description: '集成 DrawStampUtils 0.2.5 完整编辑器，支持模板、图片、毛边、防伪、做旧和 PNG 导出',
    keywords: [
      '印章',
      '电子印章',
      '印章制作',
      '印章生成',
      'drawstamp',
      'drawstamputils',
      'stamp',
      'seal',
      '模板',
      '防伪',
      '毛边',
      '做旧',
      'office',
    ],
    categoryId: 'office',
    icon: '🔴',
    type: 'window',
    windowLabel: 'tool-draw-stamp',
    windowWidth: 1480,
    windowHeight: 920,
  },
  {
    id: 'software-copyright',
    name: '软著信息提取',
    description: '从真实项目提取软件简介、主要功能、技术特点、项目分析报告和源码前后 60 页材料',
    keywords: [
      '软著',
      '软件著作权',
      '著作权',
      '版权',
      '申请材料',
      '源码材料',
      '源程序',
      '鉴别材料',
      '项目分析',
      '软件简介',
      '主要功能',
      '技术特点',
      'office',
    ],
    categoryId: 'office',
    icon: '📜',
    type: 'window',
    windowLabel: 'tool-software-copyright',
    windowWidth: 1480,
    windowHeight: 900,
  },
  {
    id: 'word-format',
    name: 'AI 文档智能整理',
    description:
      '本地整理 DOCX，支持标准排版、智能标题识别、段落结构优化、静态目录生成、关键词提取和摘要预览',
    keywords: [
      'word',
      'docx',
      'ai',
      '排版',
      '格式',
      '整理',
      '智能整理',
      '关键词',
      '摘要',
      '目录',
      '公文',
      '报告',
      '标题',
      '行距',
      '页边距',
      'office',
    ],
    categoryId: 'office',
    icon: '📝',
    type: 'window',
    windowLabel: 'tool-word-format',
    windowWidth: 1180,
    windowHeight: 820,
  },
  {
    id: 'word-duplicate-check',
    name: 'AI 文档查重',
    description: '基于本地语义模型查找 Word 文档内和多文档之间的重复、近似和改写段落',
    keywords: [
      'word',
      'docx',
      'ai',
      '查重',
      '重复',
      '相似段落',
      '语义相似',
      '文档查重',
      '报告查重',
      'office',
    ],
    categoryId: 'office',
    icon: '🔎',
    type: 'window',
    windowLabel: 'tool-word-duplicate-check',
    windowWidth: 1180,
    windowHeight: 820,
  },
  {
    id: 'word-semantic-compare',
    name: 'AI 双文档语义对比',
    description: '对比两个 Word 文档的语义覆盖率和相似段落，适合方案、合同和需求版本检查',
    keywords: [
      'word',
      'docx',
      'ai',
      '文档对比',
      '语义对比',
      '版本对比',
      '合同对比',
      '需求对比',
      '相似段落',
      'office',
    ],
    categoryId: 'office',
    icon: '🧭',
    type: 'window',
    windowLabel: 'tool-word-semantic-compare',
    windowWidth: 1180,
    windowHeight: 820,
  },
  {
    id: 'word-semantic-search',
    name: 'AI 本地文档语义搜索',
    description: '在本机 Word 文档中按语义查找相关段落，不要求关键词完全一致',
    keywords: [
      'word',
      'docx',
      'ai',
      '语义搜索',
      '文档搜索',
      '本地搜索',
      '资料搜索',
      '知识库',
      '段落检索',
      'office',
    ],
    categoryId: 'office',
    icon: '🗂️',
    type: 'window',
    windowLabel: 'tool-word-semantic-search',
    windowWidth: 1180,
    windowHeight: 820,
  },
];

export function getAllTools(): ToolDefinition[] {
  return tools;
}

export function searchTools(keyword: string): ToolDefinition[] {
  if (!keyword.trim()) return [];
  const q = keyword.toLowerCase().trim();
  return tools.filter(
    (t) => t.keywords.some((k) => k.toLowerCase().includes(q)) || t.name.toLowerCase().includes(q)
  );
}

export function getToolById(id: string): ToolDefinition | undefined {
  return tools.find((t) => t.id === id);
}

export function getToolsByCategoryId(categoryId: string): ToolDefinition[] {
  return tools.filter((t) => t.categoryId === categoryId);
}

// 兼容旧接口
export function getToolsByCategory(categoryId: string): ToolDefinition[] {
  return getToolsByCategoryId(categoryId);
}

// 保留旧的 ToolCategory 类型兼容
export type ToolCategory = string;
export const CATEGORY_LABELS: Record<string, string> = {
  ai: '人工智能',
  efficiency: '效率工具',
  text: '文本处理',
  network: '网络工具',
  download: '下载工具',
  system: '系统工具',
  dev: '开发工具',
  image: '图片处理',
  media: '音频视频',
  pdf: 'PDF 工具',
  office: '办公辅助',
  other: '其他',
};
export const ALL_CATEGORIES = [
  'ai',
  'efficiency',
  'text',
  'network',
  'download',
  'system',
  'dev',
  'image',
  'media',
  'pdf',
  'office',
  'other',
] as const;
